<?php
// Define the table HTML
$tableParams = array(
    'tableId' 	=> 'search-and-paging-container-id',
    'tableWidth' => '4', // optional (1 to 4, 1-narrow, 3-wide)
);

// create HTML for the table
echo $this->zrayTable($tableParams);
?>
<script>
(function() {
	// create the storage
	var storage = zray.getStorage('search_and_paging');

	// create the main table and bind it to the storage and HTML element
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	
	// uncomment to get Tree Table
	//var maintable = zray.createTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));

	// create columns descriptors for each column you wish to display
	maintable.setColumns([{
		label: 'Name',
		propertyName: 'name'
	}, {
		label: 'Version',
		propertyName: 'name'
	}, {
		label: 'Active?',
		propertyName: 'active'
	}]);

	// insert the data into the storage
	zray.registerDataHandler('MyWp', 'search_and_paging', function(extensionData, requestData) {
		storage.setData(extensionData);
	});

	// create pager 
	zray.createPager(storage,  jQuery('#<?php echo $params['pagerId']; ?>'));

	// create search
	zray.createSearch(storage, jQuery('#<?php echo $params['searchId']; ?>'), maintable);
})();
</script>
