<?php
// Define the table HTML
$tableParams = array(
    'tableId' 	=> 'summary-table-container-id',
    'tableWidth' => '3', // optional (1 to 4, 1-narrow, 3-wide)
	
	'summaryTableId' => 'summary-table-example-id',
	'summaryTableWidth' => '1',
);

// create HTML for the table
echo $this->zrayTable($tableParams);
?>
<script>
(function() {
	// create the storage
	var storage = zray.getStorage('summary_table');

	// create the main table and bind it to the storage and HTML element
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	
	// uncomment to get Tree Table
	//var maintable = zray.createTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));

	// create columns descriptors for each column you wish to display
	maintable.setColumns([{
		label: 'Name',
		propertyName: 'name'
	}, {
		label: 'Version',
		propertyName: 'name'
	}, {
		label: 'Active?',
		propertyName: 'active'
	}]);

	// insert the data into the storage
	zray.registerDataHandler('MyWp', 'summary_table', function(extensionData, requestData) {
		storage.setData(extensionData);
	});
	
	// create the table
	var summaryTable = zray.createSummaryTable(storage, jQuery('#<?php echo $tableParams['summaryTableId']; ?>'));

	// set by which column the user choice will filter
	summaryTable.setFilterColumn('active');

	// set callback function to create the table rows from all the data
	// return an array of rows, with columns that match to setColumns
	summaryTable.setUpdateCallback(function(data) {
		var statuses = [];
		var retVal = [];
		data.forEach(function(row) {
			if (statuses.indexOf(row.active) < 0) {
				retVal.push({active: row.active});
				statuses.push(row.active);
			}
		});
		
		return retVal;
	});


	// set the columns structure
	summaryTable.setColumns([{
		label: 'Status filter',
		propertyName: 'active', // Name of the field you want to filter 
		getHtml: function(value, record) { 
			return summaryTable.createCheckboxColumn(value, record, summaryTable) + value; 
		}
	}]);
	
	
	// create pager 
	zray.createPager(storage,  jQuery('#<?php echo $params['pagerId']; ?>'));

	// create search
	zray.createSearch(storage, jQuery('#<?php echo $params['searchId']; ?>'), maintable);
})();
</script>
